id: IF89BEC7A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:24:13+00:00'
last_modified: '2022-06-08T11:20:52.644606+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1122
  title: དབྱངས་ཅན་སྒྲ་མདོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DF4C:
      image_group_id: I1CZ1364
      title: ''
      total_pages: 24
      order: 1
      base_file: DF4C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
