id: P009482
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1122
  title: དབྱངས་ཅན་སྒྲ་མདོ
  author: ''
  volumes:
    d3da13c22e1b41c0b5afe0dd295175fb:
      image_group_id: I1CZ1364
      title: ''
      volume_number: 1
      total_pages: 24
      base_file: v001.txt
