id: P009482
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:40:47.137815
source_metadata:
  id: bdr:W1CZ1122
  title: དབྱངས་ཅན་སྒྲ་མདོ
  author: ''
  volumes:
    d3da13c22e1b41c0b5afe0dd295175fb:
      image_group_id: I1CZ1364
      title: ''
      volume_number: 1
      total_pages: 24
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
